---
# tasks file for roles/common-dependencies-cluster

- name: Installing docker
  yum:
    name: docker
    state: present

- name: Yum repo for K8s
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes
    exclude:
      - kubelet
      - kubeadm
      - kubectl
#- shell: yum install kubeadm kubelet kubectl -y --disableexcludes=kubernetes
- name: Installing kubeadm, kubelet and kubectl
  yum:
    name: 
      - kubeadm
      - kubelet
      - kubectl 
    state: present
    disable_excludes: kubernetes

- name: install iproute-tc
  package:
    name: iproute-tc
    state: present

- name: configuring ip routes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: restarting ip routes
  shell: sysctl --system

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: configuring daemon.json
  copy:
      dest: "/etc/docker/daemon.json"
      src: daemon-docker

- name: Restarting docker services
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Enabling kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
